services:
  _defaults:
    public: true

  fop.latest_products.command:
    class: FOP\Commands\LatestProducts
    tags:
      - { name: console.command }

  fop.export.command:
    class: FOP\Commands\Export
    tags:
      - { name: console.command }

  fop.status.command:
    class: FOP\Commands\ShopStatus
    tags:
      - { name: console.command }
